config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}

  
  root 'pages#home'
  
  resources :users, only: [:show, :index]
  
  resources :friendships, only: [:create, :destroy, :accept] do
    member do
      put :accept
    end
  end
  
  resources :posts, only: [:create, :edit, :update, :destroy]
  
  resources :activities, only: [:index]

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Stukbook", root_path, class: "navbar-brand" %>
    </div>
 
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        
        
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li><%= link_to "Timeline", activities_path %></li>
        <li><%= link_to "People (#{request_count})", users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= gravatar_tag current_user.email, size: 20 %><%= current_user.username %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Profile", user_path(current_user.username) %></li>
            <li><%= link_to "Friends", users_path(people: "friends") %></li>
            <li><a href="#"><%= link_to "Settings", edit_user_registration_path %></a></li>
            <li class="divider"></li>
            <li><a href="#"><%= link_to "Logout", destroy_user_session_path, method: :delete %> </a></li>
          </ul>
        </li>
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

<% flash.each do |type, message| %>
  <div class="alert alert-info fade-in">
    <button class="close" data-dismiss="alert">x</button>
    <%= message %>
  </div>
<% end %>

<%= yield %>

</body>
</html>